name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    outputs:
      reponame: ${{ steps.reponame.outputs.reponame}}

    steps:
    - uses: actions/checkout@v2
    
    - name: get repo name
      id: reponame
      run: echo "::set-output name=reponame::${GITHUB_REPOSITORY#*/}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - name: publish
      run: dotnet publish ./eShopOnWeb.sln --configuration Release -o publish
      
    - name: store zip
      run: zip -r ${{steps.reponame.outputs.reponame}}.zip publish
      
    - name: store zip
      uses: actions/upload-artifact@v2
      with:
         name: ${{steps.reponame.outputs.reponame}}
         path: ${{steps.reponame.outputs.reponame}}.zip
      
    - name: uplode artifact to azure  
      uses: bacongobbler/azure-blob-storage-upload@v1.2.0
      with:
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        source_dir: ${{steps.reponame.outputs.reponame}}
        container_name: ${{steps.reponame.outputs.reponame}}
        sync: true    
      
