name: build_pipline

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      BLOB_URL: https://sharppromotionapitest.blob.core.windows.net
       
    
    outputs:
      reponame: ${{ steps.reponame.outputs.reponame}}
      versionid: ${{ steps.versionid.outputs.versionid}}

    steps:
    - uses: actions/checkout@v2
    
    - name: get repo name
      id: reponame
      run: echo "::set-output name=reponame::${GITHUB_REPOSITORY#*/}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
      
    - name: publish
      run: dotnet publish ./eShopOnWeb.sln --configuration Release -o publish
      
    - name: version
      id: versionid
      run: echo "::set-output name=versionid::5"
      
    - name: store zip
      run: zip -r ${{steps.reponame.outputs.reponame}}_${{steps.versionid.outputs.versionid}}.zip publish
      
    - name: Uplode zip to Github
      uses: actions/upload-artifact@v2
      with:
         name: ${{steps.reponame.outputs.reponame}}_${{steps.versionid.outputs.versionid}}
         path: ${{steps.reponame.outputs.reponame}}_${{steps.versionid.outputs.versionid}}.zip

    - name: Login to Azure  Cloud with Az
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: uplode file to Blob
      run: azcopy copy '${{steps.reponame.outputs.reponame}}_${{steps.versionid.outputs.versionid}}.zip' '${{env.BLOB_URL}}/${{steps.reponame.outputs.reponame}}/${{steps.reponame.outputs.reponame}}_${{steps.versionid.outputs.versionid}}.zip${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'   
      
