name: build_pipline

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    outputs:
      reponame: ${{ steps.reponame.outputs.reponame}}
      versionid: ${{ steps.versionid.outputs.versionid}}

    steps:
    - uses: actions/checkout@v2
    
    - name: get repo name
      id: reponame
      run: echo "::set-output name=reponame::${GITHUB_REPOSITORY#*/}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
      
    - name: publish
      run: dotnet publish ./eShopOnWeb.sln --configuration Release -o publish
      
    - name: version
      id: versionid
      run: echo "::set-output name=versionid::1"
      
    - name: store zip
      run: zip -r ${{steps.reponame.outputs.reponame}}.zip publish
      
    - name: store zip
      uses: actions/upload-artifact@v2
      with:
         name: ${{steps.reponame.outputs.reponame}}
         path: ${{steps.reponame.outputs.reponame}}.zip
         
    - name: store zip
      run: |
            ls
            pwd

    - name: Login to Azure  Cloud with Az
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: uplode file
      run: azcopy copy '${{steps.reponame.outputs.reponame}}.zip' 'https://artifactstorage1.blob.core.windows.net/prasanna123/${{steps.reponame.outputs.reponame}}.zip${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'   
      
